export const theme = {
  colors: {
    primary: '#F9C406',
    primaryForeground: '#09090B',
    secondary: '#232323',
    secondaryForeground: '#fff',
    background: '#000',
    card: '#000',
    cardForeground: '#FAFAFA',
    input: '#232323',
    inputText: '#FAFAFA',
    border: '#27272A',
    text: '#FAFAFA',
    textSecondary: '#b3b3b3',
    error: '#ef4444',
    muted: '#232323',
    mutedForeground: '#b3b3b3',
    accent: '#F9C406',
    accentForeground: '#09090B',
    destructive: '#ef4444',
    destructiveForeground: '#fff',
  },
  typography: {
    h1: {
      fontSize: 28,
      fontWeight: 'bold',
      letterSpacing: 0.2,
      fontFamily: 'Outfit_700Bold',
    },
    h2: {
      fontSize: 22,
      fontWeight: 'bold',
      fontFamily: 'Outfit_700Bold',
    },
    h3: {
      fontSize: 18,
      fontWeight: 'bold',
      fontFamily: 'Outfit_700Bold',
    },
    body: {
      fontSize: 15,
      fontWeight: 'normal',
      fontFamily: 'Outfit_400Regular',
    },
    caption: {
      fontSize: 13,
      fontWeight: 'normal',
      fontFamily: 'Outfit_400Regular',
    },
    button: {
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.2,
      fontFamily: 'Outfit_700Bold',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 24,
    full: 9999,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.30,
      shadowRadius: 4.65,
      elevation: 4,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 6,
      },
      shadowOpacity: 0.37,
      shadowRadius: 7.49,
      elevation: 6,
    },
  },
}; 